let jokes = [
    "Not funny I didn't laugh. Your joke is so bad I would have preferred the joke went over my head and you gave up re-telling me the joke. To be honest this is a horrid attempt at trying to get a laugh out of me. Not a chuckle, not a hehe, not even a subtle burst of air out of my esophagus. Science says before you laugh your brain preps your face muscles but I didn't even feel the slightest twitch. 0/10 this joke is so bad I cannot believe anyone legally allowed you to be creative at all. The amount of brain power you must have put into that joke has the potential to power every house on Earth. Get a personality and learn how to make jokes, read a book. I'm not saying this to be funny I genuinely mean it on how this is just bottom barrel embarrassment at comedy. You've single handedly killed humor and every comedic act on the planet. I'm so disappointed that society has failed as a whole in being able to teach you how to be funny. Honestly if I put in all my power and time to try and make your joke funny it would require Einstein himself to build a device to strap me into so I can be connected to the energy of a billion stars to do it, and even then all that joke would get from people is a subtle scuff...",
    "The problem is you're focusing on the things in life that don't really matter. When I was a kid I had hopes and dreams. We all did. But over time, the daily grind gets in the way and you miss the things that really matter, even though they are right in front of you, staring you in the face. I think the next time you should ask yourself 'Am I on the right track here?'. I don't mean to be rude but people like you I really pity. So maybe you could use the few brain cells you have and take advantage of the knowledge I have given you now. Good luck.",
    "Haha this is so funny omg I almost spit out my caramel frappuccino with non fat coconut milk exactly 2 1/2 cups of sugar with 4 chocolate drizzles 6 1/4 pump of caramel drizzle 3 expresso shots mixed in with 3% fat without glucose, extra whip cream aswell as a Birthday cake pop with 4 strawberries on top, chocolate chips and coconut chips dried bananas and salted peanuts, roasted mango chocolate shavings coating the bottom and a handfull garlic and just a pinch of matcha powder",
    "https://www.youtube.com/watch?v=ovZq09yfZPc&ab_channel=Goofyislaughingatyoursmallpeepee",
    "Stuffer here to explain the joke! So basically, vegans often don’t eat meat because they believe it is animal cruelty. It is their way of protest. So, this person decided to try to justify eating meats by saying it is to make sure the vegans have enough food, as the cows were “stealing” their food. This is supposed to be funny (and I believe it is) because it pairs perfectly with the “no, this isn’t how you’re supposed to play the game,” which for some reason makes us laugh.",
    "Hey guys! Stuffer here to explain the joke! So basically, here is a photo of a guy on a private boat with 4 very beautiful women. Normally in such an instance, you would do something OTHER than math work. Instead, he decided to do algebra at that moment. That is why it says “there’s only one type of bra for me” “algebra,” because he is referring to the word “bra” in the “algebra.”",
    "Stuffer here to explain the joke. Here the joke is that this person girlfriend puts on a cream that makes her 10 years younger. She already is 10/younger than 10, so she disappears. It is a pedophilia joke (although depending on country and age this isn’t always considered pedophilia. I believe the reason it is funny is because it takes a while to understand, and once you get it, you’re shocked.",
    "Stuffer here to explain the joke. In a game called “Among Us”, there is usually one imposter who tries to pretend he is a crew mate and kills all the other crew mates (it can go up to a maximum of 3 imposters). Here, Jesus is hanged (if you want to know more about the Last Supper and Jesus being hanged, you should Google it. It is a deep story found within the Gospels of the Christian Bible). The real “imposter” here is Judas, but it was Jesus who was killed. The joke is that he shouldn’t have been killed. It is out into an “Among Us” meme, and boom, for anyone with a good knowledge of the Bible, it’s funny.",
    "Stuffer here to explain the joke. While a milkshake is really milk and other stuff, like ice cream, blended together, this is joking that they literally get cows, who produce milk, and spin/shake them. This is funny because it obviously is not how milk shakes are really made, and seeing a cow spin like that is simply hilarious.",
    "Stuffer here to explain the joke. Lots of times on websites you will run into a Google “Re-Captcha”. These things ask you to do dumb things like spot every traffic light. This, added with the meme that usually says things like “oh, so you like geography? Name every country” makes a meme. I believe it’s funny in most cases because it doesn’t make any sense, but in this case it is funny because it points out how stupid the Re-Captcha tests are."
];
module.exports= {
    name: "explainjoke",
    description: "this is a ping command",
    execute(message, args){
        message.channel.send(jokes[Math.floor(Math.random()*10)]);
    }
}